services:
  - type: web
    name: ater-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false   # manual डालना पड़ेगा
      - key: PYTHON_VERSION
        value: 3.11.0   # ऑप्शनल
